version: '3'

services:
  splunksrv:
    image: splunk/splunk:latest
    container_name: splunksrv
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD
    ports:
      - 8000:8000
    volumes:
      - ./mount:/logs
